### ISSUE TITLE
3D Plots are not supported (like Surface, Scatter3d)

### ISSUE THREAD

**Issue by PE1LIU** [jasrodis/dataviewer#12]
It seems that dataviewer doesn't support 3D plots like surface or scatter3d. The cause for that may lay on the webview, since I receive such error: webgl is not supported by your browser.
![image](https://user-images.githubusercontent.com/54528249/89305932-86d45e00-d66f-11ea-834b-1fdce6302fff.png)

**Comment by jasrodis** [comment]
They are using webgl and this is not supported by the engine of javafx

**Comment by PE1LIU** [comment]
Thanks for reply. Yes, I'm now aware of that.

But I have found that tablesaw (https://github.com/jtablesaw/tablesaw) of Larry can plot scatter3d (but not surface). I'm digging into it and to find the reason.

Do you maybe have an idea?

**Comment by jasrodis** [comment]
No clue, but tablesaw is a great project 👍 Have a nice day

**Comment by PE1LIU** [comment]
Solved it with jcef.
I use the browser of jcef to display the html then I can show 3D plots too.
![image](https://user-images.githubusercontent.com/54528249/93065776-6c7f9e00-f679-11ea-811a-3995938902f9.png)

**Comment by jasrodis** [comment]
👍 that sounds like a good workaround
